<?php
use Symfony\Component\HttpFoundation\RedirectResponse;
require_once __DIR__ . '/vendor/autoload.php';
/**
 * Implements hook_form_alter().
*/
function sheet_integration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
 // kint($form_id);
  $sql1="SELECT * from sheet_integration";
  $result1=db_query($sql1);
  while($data1 = $result1->fetchObject()){
    $forms[]=$data1->cid;
  }
foreach($forms as $key=>$value){
if($form_id == $value){
  $sql="SELECT * from sheet_integration where cid='".$form_id."'";
  $result=db_query($sql);
  while($data = $result->fetchObject()){
    $array=$data->client;
    $c=unserialize($array);
  }
  $form['cd']=$c;
  $form['actions']['submit']['#submit'][] = 'sheet_integration_form_submit_handler';
  }
  }
}
/**
 * Implements hook_form_submit_handler().
*/
function sheet_integration_form_submit_handler(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  $c=$form_state->getCompleteForm();
  $form_to_link=$c['#form_id'];
  $value_array[]=$form_state->getValue('name');
  $value_array[]=$form_state->getValue('mail');
  foreach ($form_state->getValues() as $key => $value) {
    if($key!='name'&& $key!='mail' && $key!='langcode' && $key!='copy')
    {
        //@@check wethr it is a date field
        if(is_object($form_state->getvalue($key)[0]['value'])){
        $value_array[]=$form_state->getValue($key)[0]['value']->format("Y-m-d H:i:s", $settings = array());
        }
        //@@check uri for links
        else if($form_state->getValue($key)[0]['uri']!=NULL){
          $value_array[]=$form_state->getValue($key)[0]['uri'];
        }
        //@code for checking boolean field type
        else if($form_state->getValue($key)['value']!=NULL){
          $value_array[]=$form_state->getValue($key)['value'];
        }
        //@@if the data is empty or null
        else if($form_state->getValue($key)[0]['value']==NULL){
          $value_array[]="not specified";
        }        
        //@@check for integer or text formats and @@check for checkboxes or select lists
        else{
          //@@check for single values
          if(sizeof($form_state->getValue($key))==1){
                $value_array[]=$form_state->getValue($key)[0]['value'];
          }
          else{
            //@@check for multiple values
            $checklist=" ";
            foreach ($form_state->getvalue($key) as $key3 => $value3) 
            {
                $checklist.=($value3['value']).' ';
            }
             $value_array[]=$checklist;   
          }
        }
    }
  }
  $id=($c['cd']);
  $sql="SELECT * from sheet_integration where cid='".$form_to_link."'";
  $result=db_query($sql);
  while($data = $result->fetchObject()){
    $sheet=$data->sheet_id;
  }
  /**
  * connects form to spreadsheet for entry of data
  */  
  $service = new Google_Service_Sheets($id);
  $spreadsheetId =$sheet;
  $range = 'Sheet1!A1:E1';
  //provide ur field values here in the format specified
  $values = array(
      $value_array
  );
  $body = new Google_Service_Sheets_ValueRange(array(
    'values' => $values
  ));
  $params = array(
    'valueInputOption' => 'RAW'
  );
  $result = $service->spreadsheets_values->append($spreadsheetId, $range, $body, $params); 
}
/**
 * Implements hook_uninstall().
*/
function sheet_integration_uninstall(){
  \Drupal::service('config.factory')->getEditable('my_sheet_int_form.settings')->delete();
}









